### PR TITLE
Remove Travis CI

### PR DESCRIPTION
**Pull request by jooola**
## PR Type

- Set minimal node version to node 8 since it has reached EOL in December 2019.
- ~Updated CI files to match maintained node versions.~
- Remove travis

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Travis isn't setup correctly at all, and isn't even on the Directus account. Lets get rid of it completely

**Comment by jooola** [comment]
Ok, done

**Comment by jooola** [comment]
@rijkvanzanten Check out https://github.com/directus/gatsby-source/tree/master/.github/workflows

**Comment by rijkvanzanten** [comment]
I actually had that before! But then GH moved from Actions beta to the real deal and the old integrations totally broke down. Haven't had the time since to update it. Wanna set it up here too?

**Comment by jooola** [comment]
@rijkvanzanten I can copy paste the setup I created for gatsby source if you like ? Let me just create a new PR

**Comment by rijkvanzanten** [comment]
Sounds good to me. I'll add the npm token once that's in 👍 

Is the gatsby source one on release or on commit to master?

**Pull request merged**
