### PR TITLE
Buildchain refactoring to tsc->rollup->uglifyjs (adds ESModule support)

### PR DESCRIPTION
**Pull request by janbiasi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines

## PR Type
What kind of change does this PR introduce?
- [x] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: Replace the build chain and add builds for ESM, ES2015, CJS and UMD

## What is the current behavior?
Compiles to UMD format only

## What is the new behavior?
Compiles to CommonJS, ESModule, ES2015 and UMD format

## Does this PR introduce a breaking change?
- [x] No

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I tried using https://github.com/ianwalter/puppeteer for the build action in the workflow instead of the regular image, but it raised another issue about a github specific file missing.

**Comment by janbiasi** [comment]
I think this is also an issue of the github workflow not supporting certain envs at the moment. There's also no GitHub compatible version of puppeteer neither any open issues which are similar to this one ... I think the best Idea would be to just skip the size-limit in the CI atm. and focus on the more important things.

**Comment by rijkvanzanten** [comment]
Agreed 👍

**Comment by rijkvanzanten** [comment]
Isn't there a separate GitHub bot plugin that does the same thing in PRs? 🤔 
I remember seeing something like that with a little overall as icon haha

**Comment by rijkvanzanten** [comment]
Ohh never mind, that was for test coverage: https://coveralls.io

There might be something like that for bundle size too 🙂

**Comment by janbiasi** [comment]
Well maybe there's something out which does that :') but it's not that important atm. so I removed it from the hooks and cleaned everything up.

**Pull request merged**
