### PR TITLE
added Typescript version of SDK

### PR DESCRIPTION
**Pull request by jlalvarez18**
@rijkvanzanten Here's the Typescript version. Feel free to update the WebPack configuration since I have no experience in it :)

I found the documentation on how to do so: https://webpack.js.org/guides/typescript

You can compile to JS by typing `tsc` into the command line.

Let me know if you have any questions.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I noticed some small differences in the actual implementation, like this method `reset`

https://github.com/directus/sdk-js/blob/master/src/index.js#L375

that's different from the same one in the typescript version. What version of the SDK is this ported of?

**Comment by rijkvanzanten** [comment]
> Whats the user case scenario where you would change the url and project

You can logout and login to a new api using the same client instance. Although you could also use the `logout` and `login` methods for that. 

I don't think that nullable is super useful, but being able to change the url on the fly might be useful if you're working with public endpoints?

I don't have a good answer to that question as I realize that I don't necessarily have a need for it myself, but I'm trying to keep an open mind. Directus gets used for a lot of different things by a lot of different people so I don't want to kill that feature too soon

**Comment by jlalvarez18** [comment]
That was exactly my thoughts. I don't see it's necessity BUT I would not be backward compatible with those mentioned cases, therefore I will fix that issue and make those properties nullable.

If we keep it, then it would require a major version bump.

**Comment by jlalvarez18** [comment]
It's your call. What do you think?

**Comment by rijkvanzanten** [comment]
I think we can drop support for overriding the URL / project / token on an active instance 👍

**Comment by jlalvarez18** [comment]
@rijkvanzanten OK.. url and project are no longer publicly writable. Let me know if there are any more modifications you would like to add.

Also feel free to make modifications to the webpack config.

**Comment by DerZade** [comment]
How is the status on this?

**Comment by jlalvarez18** [comment]
@DerZade @rijkvanzanten is there anything else you guys would like me to add?

**Comment by rijkvanzanten** [comment]
I need to find some time to make sure everything is up to date and 1-1 compatible with the current version in the build. I've never worked with TypeScript before so it's going to take me a little time to go over it....


@jlalvarez18 will this live alongside of the "regular" javascript source or will/should it replace it completely?

**Pull request merged**
